CREATE TABLE TIPO_USUARIO(
    ID_TIPO_EMPLEADO TINYINT NOT NULL AUTO_INCREMENT,
    TIPO_USUARIO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_TIPO_EMPLEADO)
);
CREATE TABLE EMPLEADOS(
    ID_EMPLEADO TINYINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    FECHA_CONTRATO DATETIME NOT NULL,
    FECHA_NACIMIENTO DATETIME NOT NULL,
    SALARIO VARCHAR(15),
    CORREO VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(50) NOT NULL,
    ID_TIPO TINYINT,
    RUT VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT fk_ID_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_USUARIO(ID_TIPO_EMPLEADO)
);

CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO TINYINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    ID_EMPLEADO TINYINT NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO),
    CONSTRAINT fk_EMPLEADO_DEPARTAMENTO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE PROYECTO(
    ID_PROYECTO TINYINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    PRIMARY KEY (ID_PROYECTO)
);

CREATE TABLE TIPO_EMPLEADO_EMPLEO(
    ID_TIPO_EMPLEADO_EMPLEO TINYINT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO TINYINT,
    ID_TIPO_EMPLEADO TINYINT,
    PRIMARY KEY (ID_TIPO_EMPLEADO_EMPLEO),
    CONSTRAINT fk_EMPLEADO_TIPO_EMPLEADO_EMPLEO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT fk_TIPO_EMPLEADO_TIPO_EMPLEADO_EMPLEO FOREIGN KEY (ID_TIPO_EMPLEADO) REFERENCES TIPO_USUARIO(ID_TIPO_EMPLEADO)
);

CREATE TABLE PROYECTO_EMPLEADO(
    ID_PROYECTO_EMPLEADO TINYINT NOT NULL AUTO_INCREMENT,
    ID_EMPLEADO TINYINT NOT NULL,
    ID_PROYECTO TINYINT NOT NULL,
    PRIMARY KEY (ID_PROYECTO_EMPLEADO),
    CONSTRAINT fk_EMPLEADO_PROYECTO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT fk_PROYECTO_PROYECTO_EMPLEADO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO(ID_PROYECTO)
);

CREATE TABLE REGISTRO_TIEMPO(
    ID_REGISTRO_TIEMPO TINYINT NOT NULL AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    CANTIDAD_HORAS TINYINT NOT NULL,
    PRIMARY KEY (ID_REGISTRO_TIEMPO)
);

CREATE TABLE ASIGNACION(
    ID_ASIGNACION TINYINT NOT NULL AUTO_INCREMENT,
    ID_DEPARTAMENTO TINYINT NOT NULL,
    ID_EMPLEADO TINYINT NOT NULL,
    PRIMARY KEY (ID_ASIGNACION),
    CONSTRAINT fk_DEPARTAMENTO_ASIGNACION FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT fk_EMPLEADO_ASIGNACION FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);
